from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
from typing import Any


class TransmitterSample:
    """
    A TransmitterSample represents a sample returned by the Transmitter.

    Attributes:
        value (float): The value generated by the Transmitter.
        node_id (int): The ID of the node that generated the sample value.
    """

    __slots__ = ("_value", "_node_id", "_frozen")

    def __init__(self, value: float, node_id: int) -> None:
        """
        Initialize a TransmitterSample.

        Args:
            value (float): The value generated by the Transmitter.
            node_id (int): The ID of the node that generated the sample value.
        """
        # value validations
        if not isinstance(value, (float, int)):
            raise TypeError("value must be a float.")
        # node_id validations
        if not isinstance(node_id, int):
            raise TypeError("node_id must be an int.")
        if node_id < 0:
            raise ValueError("node_id must be greater than or equal to 0.")
        # initializations
        super().__setattr__("_frozen", False)
        self._value = float(value)
        self._node_id = node_id
        super().__setattr__("_frozen", True)
        return

    def __repr__(self) -> str:
        """
        Get the representation of the sample.

        Returns:
            str: The representation of the sample.
        """
        result = (
            f"{self.__class__.__name__}"
            f"(value={self._value!r}, node_id={self._node_id!r})"
        )
        return result

    @property
    def value(self) -> float:
        """
        Get the value of the sample.

        Returns:
            float: The value of the sample.
        """
        return self._value

    @property
    def node_id(self) -> int:
        """
        Get the ID of the node that generated the sample value.

        Returns:
            int: The ID of the node that generated the sample value.
        """
        return self._node_id

    def __eq__(self, other: object) -> bool:
        """
        Check if two TransmitterSamples are equal.

        Args:
            other (object): The object to compare with.

        Returns:
            bool: True if the samples are equal, False otherwise.
        """
        # type validations
        if not isinstance(other, TransmitterSample):
            return NotImplemented
        # equality check
        result = self._value == other._value and self._node_id == other._node_id
        return result

    def __hash__(self) -> int:
        """
        Get the hash of the sample.

        Returns:
            int: The hash of the sample.
        """
        result = hash((self._value, self._node_id))
        return result

    def copy(self) -> TransmitterSample:
        """
        Get a copy of the sample.

        Returns:
            TransmitterSample: A copy of the sample.
        """
        result = deepcopy(self)
        return result

    def to_dict(self) -> dict[str, Any]:
        """
        Get the dictionary representation of the sample.

        Returns:
            dict[str, Any]: The dictionary representation of the sample.
        """
        result = {
            "type": self.__class__.__name__,
            "value": self._value,
            "node_id": self._node_id,
        }
        return result

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TransmitterSample:
        """
        Create a TransmitterSample from a dictionary.

        Args:
            data (dict[str, Any]): The dictionary representation of the sample.

        Returns:
            TransmitterSample: The TransmitterSample instance.
        """
        # data validations
        if not isinstance(data, dict):
            raise TypeError("data must be a dict.")
        if "type" not in data:
            raise KeyError("data must contain the key 'type'.")
        if data["type"] != cls.__name__:
            raise ValueError(f"data['type'] must be a {cls.__name__}.")
        if "value" not in data:
            raise KeyError("data must contain the key 'value'.")
        if "node_id" not in data:
            raise KeyError("data must contain the key 'node_id'.")
        # initializations
        result = cls(data["value"], data["node_id"])
        return result

    def save(self, path: str | Path, overwrite: bool = False) -> None:
        """
        Save the sample to a json file.

        Args:
            path (str | Path): The path to the file.
            overwrite (bool): Whether to overwrite the file if it exists.
        """
        # path validations
        if not isinstance(path, (str, Path)):
            raise TypeError("path must be a string or a Path.")
        # file validations
        path = Path(path)
        if path.suffix != ".json":
            raise ValueError("path must have a .json extension.")
        if not overwrite and path.exists():
            raise FileExistsError(f"path already exists: {path}.")
        # file creation
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            json.dump(self.to_dict(), f, ensure_ascii=False, indent=4)
        return

    @classmethod
    def load(cls, path: str | Path) -> TransmitterSample:
        """
        Load the sample from a json file.

        Args:
            path (str | Path): The path to the file.

        Returns:
            TransmitterSample: The TransmitterSample instance.
        """
        # path validations
        if not isinstance(path, (str, Path)):
            raise TypeError("path must be a string or a Path.")
        # file validations
        path = Path(path)
        if path.suffix != ".json":
            raise ValueError("path must have a .json extension.")
        if not path.exists():
            raise FileNotFoundError(f"path does not exist: {path}.")
        # file loading
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        result = cls.from_dict(data)
        return result

    def __setattr__(self, name: str, value: Any) -> None:
        """
        Set an attribute of the sample.

        Args:
            name (str): The name of the attribute.
            value (Any): The value of the attribute.
        """
        # freeze check
        if getattr(self, "_frozen", False):
            raise AttributeError(f"{self.__class__.__name__} is immutable.")
        # set the attribute
        super().__setattr__(name, value)
        return
