from __future__ import annotations


class TransmitterSample:
    """
    A TransmitterSample represents a sample returned by the Transmitter.

    Attributes:
        value (float): The value generated by the Transmitter.
        node_id (int): The ID of the node that generated the Sample value.
    """

    __slots__ = ("_value", "_node_id")

    def __init__(self, value: float, node_id: int) -> None:
        """
        Initialize the TransmitterSample.

        Args:
            value (float): The value generated by the Transmitter.
            node_id (int): The ID of the node that generated the Sample value.
        """
        # value validations
        if not isinstance(value, (float, int)):
            raise TypeError("value must be a float.")
        # node_id validations
        if not isinstance(node_id, int):
            raise TypeError("node_id must be an int.")
        if node_id < 0:
            raise ValueError("node_id must be greater than or equal to 0.")
        # initializations
        self._value = float(value)
        self._node_id = node_id
        return

    @property
    def value(self) -> float:
        """
        Get the value of the sample.

        Returns:
            float: The value of the sample.
        """
        return self._value

    @property
    def node_id(self) -> int:
        """
        Get the ID of the node that generated the sample value.

        Returns:
            int: The ID of the node that generated the sample value.
        """
        return self._node_id
