from __future__ import annotations

import math
import random
from dataclasses import dataclass


@dataclass(slots=True, frozen=True)
class _TransmitterSample:
    """
    A TransmitterSample represents a sample returned by the Transmitter.

    Attributes:
        value (float): The value generated by the Transmitter.
        node_id (int): The ID of the node that generated the Sample value.
    """

    value: float
    node_id: int


@dataclass(slots=True)
class _TransmitterNode:
    """
    A TransmitterNode represents a node in the Transmitter tree.

    Attributes:
        left (float): The left bound of the interval.
        right (float): The right bound of the interval.
        parent_id (int): The ID of the parent node.
        left_child_id (int): The ID of the left child node.
        right_child_id (int): The ID of the right child node.
        weight (float): The weight of the node.
        hits_left (int): The number of hits left to split the node.
        mass (float): The probability of the node being selected.
        depth (int): The depth of the node.
    """

    left: float
    right: float
    parent_id: int
    left_child_id: int
    right_child_id: int
    weight: float
    hits_left: int
    mass: float
    depth: int

    @property
    def is_leaf(self) -> bool:
        """
        Check if the node is a leaf.

        Returns:
            bool: True if the node is a leaf, False otherwise.
        """
        result = self.left_child_id == -1 and self.right_child_id == -1
        return result

    @property
    def length(self) -> float:
        """
        Get the length of the interval.

        Returns:
            float: The length of the interval.
        """
        result = self.right - self.left
        return result


class Transmitter:
    """
    The Transmitter is a data structure that learns to generate values within a given
    range (min_value, max_value).

    Attributes:
        min_value (float): The minimum value of the range.
        max_value (float): The maximum value of the range.
        initial_hits (int): The number of hits left to split the root node.
        hits_growth_rate (float): The rate at which the number of hits grows.
        learning_rate (float): The learning rate of the Transmitter.
        min_weight (float): The minimum weight of a node.
        max_weight (float): The maximum weight of a node.
        min_interval_width (float): The minimum width of an interval.
        max_depth (int | None): The maximum depth of the Transmitter tree.
        seed (int | None): The seed for the random number generator.
        rng (random.Random): The random number generator.
        nodes (list[_TransmitterNode]): The list of nodes in the Transmitter tree.
        root_id (int): The ID of the root node.
    """

    def __init__(
        self,
        min_value: float,
        max_value: float,
        *,
        initial_hits: int = 1,
        hits_growth_rate: float = 1.1,
        learning_rate: float = 0.01,
        min_weight: float = 1e-9,
        max_weight: float = 1e9,
        min_interval_width: float = 1e-9,
        max_depth: int | None = None,
        seed: int | None = None,
    ) -> None:
        """
        Initialize the Transmitter.

        Args:
            min_value (float): The minimum value of the range.
            max_value (float): The maximum value of the range.
            initial_hits (int): The number of hits left to split the root node.
            hits_growth_rate (float): The rate at which the number of hits grows.
            learning_rate (float): The learning rate of the Transmitter.
            min_weight (float): The minimum weight of a node.
            max_weight (float): The maximum weight of a node.
            min_interval_width (float): The minimum width of an interval.
            max_depth (int | None): The maximum depth of the Transmitter tree.
            seed (int | None): The seed for the random number generator.
        """
        # min_value & max_value validations
        if not isinstance(min_value, (float, int)):
            raise TypeError("min_value must be a float.")
        if not isinstance(max_value, (float, int)):
            raise TypeError("max_value must be a float.")
        if min_value >= max_value:
            raise ValueError("min_value must be lower than max_value.")
        # initial_hits validations
        if not isinstance(initial_hits, int):
            raise TypeError("initial_hits must be an int.")
        if initial_hits <= 0:
            raise ValueError("initial_hits must be greater than 0.")
        # hits_growth_rate validations
        if not isinstance(hits_growth_rate, (float, int)):
            raise TypeError("hits_growth_rate must be a float.")
        if hits_growth_rate <= 0:
            raise ValueError("hits_growth_rate must be greater than 0.")
        # learning_rate validations
        if not isinstance(learning_rate, (float, int)):
            raise TypeError("learning_rate must be a float.")
        if learning_rate <= 0:
            raise ValueError("learning_rate must be greater than 0.")
        # min_weight & max_weight validations
        if not isinstance(min_weight, (float, int)):
            raise TypeError("min_weight must be a float.")
        if not isinstance(max_weight, (float, int)):
            raise TypeError("max_weight must be a float.")
        if min_weight <= 0:
            raise ValueError("min_weight must be greater than 0.")
        if min_weight >= max_weight:
            raise ValueError("min_weight must be lower than max_weight.")
        # min_interval_width validations
        if not isinstance(min_interval_width, (float, int)):
            raise TypeError("min_interval_width must be a float.")
        if min_interval_width <= 0:
            raise ValueError("min_interval_width must be greater than 0.")
        # max_depth validations
        if max_depth is not None:
            if not isinstance(max_depth, int):
                raise TypeError("max_depth must be an int.")
            if max_depth <= 0:
                raise ValueError("max_depth must be greater than 0.")
        # seed validations
        if seed is not None:
            if not isinstance(seed, int):
                raise TypeError("seed must be an int.")
        # initializations
        self.initial_hits = initial_hits
        self.hits_growth_rate = float(hits_growth_rate)
        self.learning_rate = float(learning_rate)
        self.min_weight = float(min_weight)
        self.max_weight = float(max_weight)
        self.min_interval_width = float(min_interval_width)
        self.max_depth = max_depth
        self.rng = random.Random(seed)
        # tree represented as a list of node indices (not pointers)
        self.nodes: list[_TransmitterNode] = []
        # root node
        root_weight = 1.0
        root = _TransmitterNode(
            left=float(min_value),
            right=float(max_value),
            parent_id=-1,
            left_child_id=-1,
            right_child_id=-1,
            weight=root_weight,
            hits_left=initial_hits,
            mass=root_weight * (float(max_value) - float(min_value)),
            depth=0,
        )
        self.nodes.append(root)
        self.root_id = 0
        return

    def forward(self) -> _TransmitterSample:
        """
        Generate a sample from the Transmitter.

        Returns:
            _TransmitterSample: The sample generated by the Transmitter.
        """
        node_id = self.root_id
        node = self.nodes[node_id]
        # sample a value from the root's mass
        r = self.rng.random() * node.mass
        while True:
            # if node is a leaf, sample a uniform value from the leaf's interval
            if node.is_leaf:
                value = self.rng.uniform(node.left, node.right)
                sample = _TransmitterSample(
                    value=value,
                    node_id=node_id,
                )
                break
            # decide which child to go to
            left_mass = self.nodes[node.left_child_id].mass
            if r < left_mass:
                node_id = node.left_child_id
            else:
                # translate value to the right child's mass
                r -= left_mass
                node_id = node.right_child_id
            node = self.nodes[node_id]
        return sample

    def backward(self, sample: _TransmitterSample, feedback: float) -> None:
        """
        Update the Transmitter based on the given feedback.

        Args:
            sample (_TransmitterSample): The sample associated with the feedback.
            feedback (float): The feedback from the environment used to update
                the Transmitter.
        """
        # sample validations
        if not isinstance(sample, _TransmitterSample):
            raise TypeError("sample must be a TransmitterSample")
        # feedback validations
        if not isinstance(feedback, (float, int)):
            raise TypeError("feedback must be a float")
        if not (-1.0 <= feedback <= 1.0):
            raise ValueError("feedback must be in [-1, 1]")
        # find the leaf node that contains the sample
        node_id = sample.node_id
        node = self.nodes[node_id]
        if not node.is_leaf:
            node_id = self._find_leaf(node_id, sample.value)
            node = self.nodes[node_id]
        # update weight & mass
        node.weight = self._clip_weight(
            node.weight * math.exp(self.learning_rate * float(feedback))
        )
        self._propagate_mass_up(node_id)
        # split if needed
        node.hits_left -= 1
        if self._should_split(node_id):
            self._split_leaf(node_id)
        return

    def _find_leaf(self, node_id: int, value: float) -> int:
        """
        Find the leaf node that contains the given value.

        Args:
            node_id (int): The ID of the node to start the search from.
            value (float): The value to find the leaf node for.

        Returns:
            int: The ID of the leaf node that contains the given value.
        """
        node = self.nodes[node_id]
        while not node.is_leaf:
            if value < self.nodes[node.left_child_id].right:
                node_id = node.left_child_id
            else:
                node_id = node.right_child_id
            node = self.nodes[node_id]
        return node_id

    def _clip_weight(self, weight: float) -> float:
        """
        Clip the given weight to the range [min_weight, max_weight].

        Args:
            weight (float): The weight to clip.

        Returns:
            float: The clipped weight.
        """
        if weight < self.min_weight:
            weight = self.min_weight
        elif weight > self.max_weight:
            weight = self.max_weight
        return weight

    def _propagate_mass_up(self, node_id: int) -> None:
        """
        Propagate the mass up the tree.

        Args:
            node_id (int): The ID of the node to start the propagation from.
        """
        while node_id != -1:
            node = self.nodes[node_id]
            # update the mass of the current node
            if node.is_leaf:
                node.mass = node.weight * node.length
            else:
                node.mass = (
                    self.nodes[node.left_child_id].mass
                    + self.nodes[node.right_child_id].mass
                )
            node_id = self.nodes[node_id].parent_id
        return

    def _should_split(self, node_id: int) -> bool:
        """
        Determine if the given node should be split.

        Args:
            node_id (int): The ID of the node to check.

        Returns:
            bool: True if the node should be split, False otherwise.
        """
        node = self.nodes[node_id]
        result = True
        if not node.is_leaf:
            result = False
        elif node.hits_left > 0:
            result = False
        elif self.max_depth is not None and node.depth >= self.max_depth:
            result = False
        elif node.length * 0.5 < self.min_interval_width:
            result = False
        return result

    def _split_leaf(self, node_id: int) -> None:
        """
        Split the given leaf node into two child nodes.

        Args:
            node_id (int): The ID of the node to split.
        """
        node = self.nodes[node_id]
        if not node.is_leaf:
            raise ValueError("node_id must be a leaf node.")
        node_mid = (node.left + node.right) * 0.5
        left_child_id = len(self.nodes)
        right_child_id = left_child_id + 1
        child_weight = node.weight
        child_depth = node.depth + 1
        child_hits_left = math.ceil(
            self.initial_hits * (child_depth + 1) ** self.hits_growth_rate
        )
        # create child nodes
        left_child_node = _TransmitterNode(
            left=node.left,
            right=node_mid,
            parent_id=node_id,
            left_child_id=-1,
            right_child_id=-1,
            weight=child_weight,
            hits_left=child_hits_left,
            mass=child_weight * (node_mid - node.left),
            depth=child_depth,
        )
        right_child_node = _TransmitterNode(
            left=node_mid,
            right=node.right,
            parent_id=node_id,
            left_child_id=-1,
            right_child_id=-1,
            weight=child_weight,
            hits_left=child_hits_left,
            mass=child_weight * (node.right - node_mid),
            depth=child_depth,
        )
        self.nodes.append(left_child_node)
        self.nodes.append(right_child_node)
        node.left_child_id = left_child_id
        node.right_child_id = right_child_id
        return
